### ISSUE TITLE
Server version unavailable

### ISSUE THREAD

**Issue by PetrMa** [Chucy/icinga2_vmware_snapshots#1]
Dear developer,
today I made an upgrade of my Debian server from veresion 9 to version 10.
All vmware plugins works fine except your plugin.
Every time I´ve got an error:
Server version unavailable at 'https://servername:443/sdk/vimService.wsdl' at /usr/share/perl/5.28/VMware/VICommon.pm line 704.

Have you any idea how to fix the script to fully working?

Thanks, Regards,
Petr

**Comment by PetrMa** [comment]
Hello,
it seems I found the issue. I changed your script from:

**$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;**

to

**BEGIN {
    $ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;
    eval {
        # required for new IO::Socket::SSL versions
        require IO::Socket::SSL;
        IO::Socket::SSL->import();
        IO::Socket::SSL::set_ctx_defaults( SSL_verify_mode => 0 );
    };
};**

**Comment by Chucy** [comment]
Hello,
i've updated the script according to your Solution. Thank you for finding a solution to the Problem.

Regards,
Chucy
