### ISSUE TITLE
whitelist based on snapshotname not working

### ISSUE THREAD

**Issue by xefil** [Chucy/icinga2_vmware_snapshots#2]
Hello,

I'm testing your script but the whitelist based on the snapshot name is not working.
If I test it with a whitelist name of the VM, the I get only the snapshots matching age/count of the selected vm name. The same is not working if I try to find out the snapshosts with a given name. This because I'm trying to find out snapshots with a particolare name, created by a backup istance.
Could you help me?
Thanks!

Simon

**Comment by xefil** [comment]
Here an example:

```
./check_vmware_snapshots.pl --password 'XXX' --username 'XXX' --server XXX --mode age --warning 0 --critical 0 --whitelist 'MY-VM-NAME'     
CRITICAL - 1 outdated VM snapshots found!, Snapshot "MY-SNAPSHOT-NAME" (VM: 'MY-VM-NAME') is 429 days old | outdated_snapshots=1snapshots;0;0

./check_vmware_snapshots.pl --password 'XXX' --username 'XXX' --server XXX --mode age --warning 0 --critical 0 --whitelist 'MY-SNAPSHOT-NAME' --match_snapshot_names=1  
OK - No outdated VM snapshots found. | outdated_snapshots=0snapshots;0;0
```

Ideas?
Thanks!!

Simon

**Comment by redhat-linux** [comment]
Hello 

I have the same issue, Whitelist and blacklist doesn't work 
or any Ideas How I can exclude a VM machine ?  

Thank you 
Ali

**Comment by Chucy** [comment]
Hello

i finally got time to try the whitelist/blacklist feature. Black and Whitelisting of vmnames and snapshotnames work in my work environment. One thing that i noticed in your command is that  "--match_snapshot_names=1 " should be "--match_snapshot_names 1". I hope i could help.
Regards
Patrick

**Comment by xefil** [comment]
Hello!
Thanks for the update.
BTW I've applied a little mod because I've seen it matches vm name AND vm snapshot name, but my goal was to search only the vm snapshotname on ANY vms.
I've solved it, in case you need it, let me know ;-)
Thanks for your suggestions as well!
Cheers, Simon

**Comment by Chucy** [comment]
Hello Simon,
i'm glad that you found a solution. I really would like to know how you solved it.
Cheers, Patrick

**Comment by redhat-linux** [comment]
> Hello!
> Thanks for the update.
> BTW I've applied a little mod because I've seen it matches vm name AND vm snapshot name, but my goal was to search only the vm snapshotname on ANY vms.
> I've solved it, in case you need it, let me know ;-)
> Thanks for your suggestions as well!
> Cheers, Simon

Hello!
would you please share it with me ?
thank you

**Comment by xefil** [comment]
Hello!
Sorry, I don't know if it helps for you, btw there the easy mod.
As written the original script checks for snapshot name AND vm name. I need to search for a given name in ALL the snapshots. Here we are:
On line `223` you shoud find:
```
next if (isnotwhitelisted(\$whitelist,$vm_name));
```
I've included it into a simple if, looking like that:
```
    if ($match_snapshot_names == 0) {
      next if (isnotwhitelisted(\$whitelist,$vm_name));
    }
```

Let me know if it works.
Bye, Simon
